#!/bin/bash
#if [ $# -ne 1 ]
#then
if (( $# < 1 )); then
    echo "USAGE: expvpn option"
    echo "options;"
    echo "secure    shows if IP is secure or not"
    echo "ip        the current IP"
    echo "location  shows the location of you ip"
    echo "status    shows if connected"
    echo "show      show current server"
    echo "list      list servers"
    echo "switch    switch to server IE expvpn switch someplace.expressnetw.com:1195"
    echo "start     start vpn connection"
    echo "stop      stop vpn connection"
    echo "help      this help"
exit
#return
fi
main() {
   case "$1" in
    secure)
        POOP=$(curl -s https://www.expressvpn.com/what-is-my-ip | grep -m 1 "Your IP address")
        [[ "$POOP" == "Your IP address is secured." ]] && echo "Your IP address is secured." || echo "Your IP address is Not Secured"
        return
        ;;
    ip)
        curl -s https://www.expressvpn.com/what-is-my-ip | grep -m 1 -A3 "Your" | grep -v "h4\|class" | grep -v Your 2> /dev/null
        return
        ;;
    location)
        curl -s https://www.expressvpn.com/what-is-my-ip | grep -m 1 -A4 "Location" | grep -v "h4\|class" | grep -v Location 2> /dev/null
        return
        ;;
    status)
        nmcli connection show expressvpn | grep -i VPN.VPN-STATE > /dev/null && echo Connected || echo "Not Connected"
        return
        ;;
    help)
        echo "USAGE: expvpn option"
        echo "options;"
        echo "secure    shows if IP is secure or not"
        echo "ip        the current IP"
        echo "location  shows the location of you ip"
        echo "status    shows if connected"
        echo "show      show current server"
        echo "list      list servers"
        echo "switch    switch to server IE expvpn switch someplace.expressnetw.com:1195"
        echo "help      this help"
        echo "start     start vpn connection"
        echo "stop      stop vpn connection"
        return
        ;;
    start)
        nmcli connection up expressvpn
        return
        ;;
    stop)
        nmcli connection down expressvpn
        return
        ;;
    switch)
        nmcli connection modify expressvpn +vpn.data remote=$2
        return
        ;;
    show)
        cur-server
        return
        ;;
    list)
        cat /usr/share/expvpn/server-list-udp-url-port
        return
        ;;
    esac
}

get_ip() {
    RADDR=$(curl -s https://ipinfo.io/ip)
    echo "remote ip: $RADDR"
}

main "${@}"
